### PR TITLE
Added Chips for removable filters

### PR DESCRIPTION
**Pull request by TheGooner93**
This solves https://github.com/code-for-cause/tech-conferences/issues/17

### CODE REVIEW

**Comment by TheGooner93** [comment]
@vikaskyadav  have a look

**Comment by vikaskyadav** [comment]
great @TheGooner93 this looks  great. Will you be able to make one more small change? Can't we do something so that if the number of tags is more, instead of going on `scroll`, they come in the `next row`?

**Comment by TheGooner93** [comment]
as such, the responsiveness of the entire page needs to also be handled, even the table contents are not very responsive, just like the wordcloud. Can i suggest it to be done as part of a separate issue instead of the same one?

**Comment by TheGooner93** [comment]
@vikaskyadav I have made the change, have a look

**Comment by vikaskyadav** [comment]
Great ! We'll do work for responsiveness in another issue.

**Pull request merged**
