### PR TITLE
Integration with Google Firebase

### PR DESCRIPTION
**Pull request by TheGooner93**
Implemented: 
1. Login/Logout against Firebase
2. Addition of events to logged in users from Firestore

### CODE REVIEW

**Comment by TheGooner93** [comment]
H, @vikaskyadav ; resolved some merge conflicts. Have a look.
I tried adapting as much as possible, based on the changes for the filtering by event name.

**Comment by TheGooner93** [comment]
Hi, what issue are you facing? Any specific errors?

**Comment by vikaskyadav** [comment]
I have mentioned the package.json file issue above. Just have a look at it.

**Comment by vikaskyadav** [comment]
@TheGooner93 yeah everything working fine. Great Job!

**Comment by TheGooner93** [comment]
Hi there,
I am yet to submit work from Gitcoin ,since it requires Ether which i dont
own as of now.

Thanks and regards
Mohammed Ehab

**Comment by vikaskyadav** [comment]
Closes #1

**Pull request merged**
